spring.application.name=backend
# DataSource Configuration
spring.datasource.url=jdbc:mysql://kodama.proxy.rlwy.net:57793/railway
spring.datasource.username=root
spring.datasource.password=QXZrgXhlptxuaxpSwQODYIvujpnDpqZU
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate/JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=${PORT:8080}

